<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmartHal.Core.Secrets</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartHal.Core.Shared\SmartHal.Core.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CreativeCoders.Core" />
    <PackageReference Include="Devlooped.CredentialManager" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
