<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmartHal.Core.Adapters</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartHal.Core.Shared\SmartHal.Core.Shared.csproj" />
    <ProjectReference Include="..\SmartHal.Core.Devices\SmartHal.Core.Devices.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CreativeCoders.Core" />
  </ItemGroup>

</Project>
