<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmartHal.Core.Backup</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SmartHal.Core.Backup.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartHal.Core.Shared\SmartHal.Core.Shared.csproj" />
    <ProjectReference Include="..\SmartHal.Core.Devices\SmartHal.Core.Devices.csproj" />
    <ProjectReference Include="..\SmartHal.Core.Config\SmartHal.Core.Config.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
    <PackageReference Include="CreativeCoders.Core" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
